### PR TITLE
Sqlite3 changes

### PR DESCRIPTION
**Pull request by jdodgen**
sqlite3-busy-timeout feature to allow a wait time when database is locked.

Configure looks in the motion source for the sqlite3 amalgamation  (sqlite3.c file) and uses this
if not found the shared library is used.  Note: both the sqlite3.h and sqlite3.c files need to exist.

### CODE REVIEW

**Comment by jdodgen** [comment]
My last push did a bunch of "coding standards" fixes as it left my editor,  Converting tabs to spaces.  If you wish I'll redo the changes and let it save with the tabs.

**Comment by Mr-Dave** [comment]
We'll have to look at this a bit more.  Line 2742 does not compile when SQLLite is not installed.

**Comment by tosiara** [comment]
Yeah, I can confirm that:
```
./configure --without-sqlite3 && make
```
gives error:
```
Compiling Motion object files...
--------------------------------------------------------------------------------
gcc -g -O2 -D_REENTRANT -DHAVE_FFMPEG -I/usr/include -DFFMPEG_NEW_INCLUDES -DHAVE_FFMPEG_NEW -DMOTION_V4L2 -DMOTION_V4L2_OLD -DTYPE_32BIT="int" -DHAVE_BSWAP   -march=native -mtune=native -Wall -DVERSION=\"Unofficial-Git-d71cebf\" -Dsysconfdir=\"/usr/local/etc\"    -c -o motion.o motion.c
motion.c: In function 'main':
motion.c:2742:24: error: 'struct context' has no member named 'database_sqlite3'
motion.c:2742:54: error: 'struct context' has no member named 'database_sqlite3'
make: *** [motion.o] Error 1
```
This change seems to fix:
```
diff --git a/motion.c b/motion.c
index 5575bc4..d2ef8cb 100644
--- a/motion.c
+++ b/motion.c
@@ -2739,7 +2739,9 @@ int main (int argc, char **argv)
                        cnt_list[i]->conf.stream_port);
             /* this is done to share the seralized handle
              * and supress creation of new handles in the threads */
+#ifdef HAVE_SQLITE3
             cnt_list[i]->database_sqlite3=cnt_list[0]->database_sqlite3;
+#endif
             start_motion_thread(cnt_list[i], &thread_attr);
         }
```
But I wonder

**Comment by jdodgen** [comment]
I reverted the tab to spaces changes.
Also added the ifdef causing the compile to fail when NOT using sqlite

**Comment by Mr-Dave** [comment]
I applied this patch and also installed sqllite3 from the standard Ubuntu repos (14.04 x64) without any further configuration to sqllite3 and this patch causes a segfault on startup.  Were any of the other commits addressing this?

**Comment by jdodgen** [comment]
I'll check this out in three days when I return

*Jim Dodgen*

**Comment by jdodgen** [comment]
My bad, I had not test with sqlite included and no config file, or missing
database stuff in the config file.  added a null pointer check for
database_type


*Jim Dodgen*

**Comment by Mr-Dave** [comment]
Jim, I have not forgotten about this pull request.  However, I've been asked to try to limit the number of commits in the repo so that changes can be tracked easier and this pull has lots of commits related to the whitespace changes.  I'm also relatively new to git and will take some time to offer a suggestion for getting these changes included.  We'll also have to see how to get the segfault fix into the pull.

**Pull request merged**
