### PR TITLE
SQLite3 busy timeout

### PR DESCRIPTION
**Pull request by jdodgen**
Added sqlite3_busy_timeout to allow a wait time before returning a database locked condition

### CODE REVIEW

**Comment by Mr-Dave** [comment]
I am good with the SQLite stuff but I think that if the config file check is implemented, functionality would be lost.  Some people may have scripts that rely upon the existing behaviour that lets things fall through and go searching rather than having a hard error/rejection.  There are lots of warnings in the code below that were built to report the situation.  (I don't think I'd want to code scripts like that relying upon defaults but there are lots of use cases of motion that I don't know about...)

**Comment by jdodgen** [comment]
I can live with out the config check.

I just thought that if some one was expecting to see a behavior that was
expected in the config they passed in and it was doing something different
that this would help.

*Jim Dodgen*

**Comment by tosiara** [comment]
I too would like to split sqlite apart from config changes. Since it will change the behavior and may affect users. But you can still create and leave your pull open just for everyone to see this change. The more users find it usefull and merge to their trees - the bigger possibility to merge it upstream later. FWIW

**Comment by jdodgen** [comment]
This all sounds fine to me.  I  need the conf in my application because I want to  know what config I'm using.  I build the configs and run motion from a Perl program and like the error check. Any 

Being a github novice, how do I start a new pull.  All my "svn ci's" get/got appended to #69.

**Comment by tosiara** [comment]
I would create a separate local branch for every pull. For example:

git clone https://gihub/MrDave
cd MrDave
git checkout unstable -b sqlite-patch
# make your changes and commit as many times as you like --
git push origin sqlite-path
Now you have a branch on your github that only contains sqlite related changes

Then you can create another branch for config changes by checking out "unstable" again:
git checkout unstable -b conf-patch
... etc

**Comment by jdodgen** [comment]
Excellent, thanks


*Jim Dodgen*

**Comment by jdodgen** [comment]
more help please

git clone https://gihub/MrDave?

I assume you meant? 
git clone https://github.com/Mr-Dave  
which gives me a "not found"

**Comment by tosiara** [comment]
```
git clone https://github.com/Mr-Dave/motion.git
```

**Comment by jdodgen** [comment]
Sorry to bother again,

It created "motion"  so I continued ...

jim@dev:~/motion$ git checkout unstable -b sqlite-patch
fatal: Cannot update paths and switch to branch 'sqlite-patch' at the same time.
Did you intend to checkout 'unstable' which can not be resolved as commit?

**Comment by tosiara** [comment]
Hm, I thought I used to checkout and branch at the same time.
Nevermind, just spit the command:
```
# git checkout unstable
Branch unstable set up to track remote branch unstable from origin.
Switched to a new branch 'unstable'
# git checkout -b sqlite-patch
Switched to a new branch 'sqlite-patch
```

**Comment by jdodgen** [comment]
One baby step at a time :)

jim@dev:~/motion$ git push origin sqlite-patch
Username for 'https://github.com': jdodgen
Password for 'https://jdodgen@github.com': 
remote: Permission to Mr-Dave/motion.git denied to jdodgen.
fatal: unable to access 'https://github.com/Mr-Dave/motion.git/': The requested URL returned error: 40

**Comment by tosiara** [comment]
This is expected :)
Start from `git clone https://github.com/jdodgen/motion.git`

**Pull request closed without merging**
