### PR TITLE
Hevc

### PR DESCRIPTION
**Pull request by momo-i**
I am not familiar with git(and github). I would be the various ways code changes / additions, because it does not know how to pull request with the necessary commit ID, I've created a new branch. And I was re-commit the only modification of hevc there. Sorry for dirty log.

### CODE REVIEW

**Comment by tosiara** [comment]
@Mr-Dave final patch looks pretty innocent: 14 additions and 3 deletions

**Comment by Mr-Dave** [comment]
There is a lot of commits in there.  What if we merged at the point that you merged my latest master branch.  041797709d8186bfb2e99670fe597856cdb9bb2f ?  
I'm not sure how this will look on the github network graph but in GIT DAG it looks 
a bit strange but generally OK.  Your changes appear on the main line and 
my changes are branching around them and back in.  If you want to look at it, 
the following are the commands that I ran
to test it.  I'd recommend doing this in an empty directory so that your regular
work doesn't get messed up.  I'll let you know that I've not done a merge this 
way before and I'm still new to git.  If anyone else knows a better strategy, please comment.
git clone https://github.com/mr-dave/motion.git 
cd motion
git checkout -b momo-i-hevc master
git pull https://github.com/momo-i/motion.git hevc
git checkout master
git merge -s recursive -X theirs 041797709d8186bfb2e99670fe597856cdb9bb2f 

I also tried to just create a pull request at that point but it wasn't let me do if on my own repo.  It appears that you can do a pull request and where it is asking for the branch, you just put in the commit id.  It may work doing it from your repo though since it was forked from me.  

Once the merge is done, then I'll make that last change in the ELSE section
and also add you into the CHANGELOG.  Since it looks like ffmpeg changed some of 
their API's I have to be in there anyways.

**Comment by momo-i** [comment]
@Mr-Dave I merged that your latest branch is 0417977.

**Comment by Mr-Dave** [comment]
What I was trying to get confirmation on was to merge in at that commit point where you merged from my master.  The statements that I indicated are only going to bring in the first two commits of your changes and leave off the Test and Revert ones.  This will leave the code tree much cleaner.

**Pull request closed without merging**
