### PR TITLE
V4L2 missing a #include videodev2.h

### PR DESCRIPTION
**Pull request by jdodgen**
track.c compiles with errors if omitted,

### CODE REVIEW

**Comment by tosiara** [comment]
What OS were you using when you got compilation errors?
I noticed that some systems allow you to compile without any issues, but some require that hack. We need to identify the root cause before fixing, and test more

**Comment by jdodgen** [comment]
Ubuntu 14.04 LTS 32bit

*Jim Dodgen*

**Comment by tosiara** [comment]
Ubuntu 13.10 32bit - no issues
Ubuntu 14.04 32bit - no issues
openSUSE 13.2 64bit - no issues
openSUSE 12.3 32bit - needs hack

**Comment by tosiara** [comment]
At least in openSUSE removing `-DMOTION_V4L2` gcc flag resolves the issue. So it may be configure issue, not the code

**Comment by jdodgen** [comment]
removing -DMOTION_V4L2 on my system fixes the problem also


*Jim Dodgen*

**Comment by jdodgen** [comment]
Well, it does compiler when -DMOTION_V4L2 & the videodev2.h include in
track.c are removed
but, I get "invalid device" when taking pictures from my BT878

I put them back and get good pictures

*Jim Dodgen*

**Comment by jdodgen** [comment]
I was wrong in my last comment, the removal of  -DMOTION_V4L2 does fix
things.

*Jim Dodgen*

**Comment by tosiara** [comment]
Great. Now we could think about the root cause and try to fix configure.ac. Any ideas?

**Comment by jdodgen** [comment]
Sounds like fun,

Ok, let me see if I have the facts straight

For openSUSE 32bit the -DMOTION_V4L2 needs to be removed

Most Ubuntu 14.04 LTS versions work fine with -DMOTION_V4L2

My and I expect other Ubuntu 14.04 LTS 32bit needs -DMOTION_V4L2  to be
removed

So we need to come up with a way to detect the differences.

My gut feeling is that it may have to do with the way the v4l stuff is
installed, I think mine came in when I installed streamer, which I'm
replacing with motion.


*Jim Dodgen*

**Comment by jdodgen** [comment]
Digging around ....

In video2.c I see on line 76 the following

---
#if !defined(WITHOUT_V4L) && defined(MOTION_V4L2)
#include "motion.h"
#include "video.h"

#ifdef MOTION_V4L2_OLD
// Seems that is needed for some system
#include <linux/time.h>
#include <linux/videodev2.h>
#endif
...

so It seems this has popped up in the past.

 Also track.c has seen some recent changes and needed to add videoio.h

would this cause any breakage if videodev2 were wrapped  in #ifdef
MOTION_V4L2_OLD in track.c?




*Jim Dodgen*

**Comment by tosiara** [comment]
Can you check on your Ubuntu 14 following command:
```
ls /usr/include/linux/videodev.h /usr/include/libv4l* -l
```
On my openSUSE 12.3 I see a symlink exists to `/usr/include/linux/videodev.h -> ../libv4l1-videodev.h`
Removing this symlink resolves compilation issue

**Comment by jdodgen** [comment]
Same soft link here:

ls /usr/include/linux/videodev.h /usr/include/libv4l* -l
-rw-r--r-- 1 root root  2918 Jan 13  2014 /usr/include/libv4l1.h
-rw-r--r-- 1 root root  7135 Jan 13  2014 /usr/include/libv4l1-videodev.h
-rw-r--r-- 1 root root  4725 Jan 13  2014 /usr/include/libv4l2.h
-rw-r--r-- 1 root root 14594 Jan 13  2014 /usr/include/libv4l2rds.h
-rw-r--r-- 1 root root  5801 Jan 13  2014 /usr/include/libv4lconvert.h
-rw-r--r-- 1 root root  1757 Jan 13  2014 /usr/include/libv4l-plugin.h
lrwxrwxrwx 1 root root    31 Apr 27  2013 /usr/include/linux/videodev.h ->
/usr/include/libv4l1-videodev.h

I unlinked it and now it compiles,  link still fails without the
" -lswresample -lva" libs



*Jim Dodgen*

**Comment by Mr-Dave** [comment]
I just built a raw 14.04.2 machine and updated everything and it compiled fine.  This is a strange one.  I'll see if I can track down the root cause and see if there would be any degrading if it is just added anyway.

**Comment by Mr-Dave** [comment]
Can each of you give me your ideas on this pull request?  I am unable to reproduce this issue and the conversation seems to indicate the issue lies with the configure rather than the file being proposed to be changed.

**Comment by tosiara** [comment]
I vote for rejecting thins pull, because the root cause related to config and requires more investigation

**Comment by jdodgen** [comment]
Sounds good to me, if no one else is having the problem then it must be
related to the way my Ubuntu system has been configured over time through
upgrades and installs.

*Jim Dodgen*

**Comment by tosiara** [comment]
It's not just you having that issue. There were many users. 
The problem is with this patch: it supposed to be just a quick workaround to allow compilation, and to be committed into source tree. Because it is a workaround, not a permanent fix

**Comment by Mr-Dave** [comment]
I reviewed some of the other code and there is precedent.  video2.c also has this include and I believe references the same items that cause track.c to fail.  I'm guessing that the tracking module was added after this was first reported.  One thing to note that the pull uses MOTION_V4L2 versus the video.c uses MOTION_V4L2_OLD.  I'm going to merge this pull and then add another commit to revise it to use _OLD.  The configure does need additional work however since even on my machines, I get both the flags and it should only be flagging those that need the MOTION_V4L2_OLD.

**Pull request merged**
