### PR TITLE
Unstable

### PR DESCRIPTION
**Pull request by jdodgen**
My first pull request.  my changes are mostly adding the ability to extend/modify the time a database will wait before returning a locked error.

### CODE REVIEW

**Comment by tosiara** [comment]
You have issued pull request from "unstable" into "master". This is wrong. You should do "unstable"->"unstable". Can you recreate your pull request?

**Comment by jdodgen** [comment]
Ok, I think I did it correct this time.  feed back please.

*Jim Dodgen*

**Comment by jdodgen** [comment]
anyway to delete the bad pull?

*Jim Dodgen*

**Comment by tosiara** [comment]
I think pull author can just Close it without merging. Do you see Close button anywhere?

**Comment by Mr-Dave** [comment]
Thanks Tosiara.  I'll close it on my end and look at the other one.

**Comment by jdodgen** [comment]
ok, I'll remove the offending libs and include and issue another pull, it
will be another day I'm away from my development machine.

*Jim Dodgen*

**Comment by jdodgen** [comment]
I also closed #67

*Jim Dodgen*

**Comment by jdodgen** [comment]
well I blew away my 'unstable' by accident, thought it was needed. thought
I was keeping things "tidy" from this advice.

https://help.github.com/articles/closing-a-pull-request/

just my github learning curve ...

I'll get it all back soon

*Jim Dodgen*

**Comment by tosiara** [comment]
You can drop the whole your fork through the web interface, then re-fork @Mr-Dave repo and start from scratch. That's not a big deal, I do that sometimes when completely screw the working tree :)

**Comment by jdodgen** [comment]
Ok, I dropped the problem fork and created a new one, the pull I'll do in a
minute is for just the sqlite3 busy timeout

A question:

track.c >  #include <linux/videodev2.h>   is not in the pull, but I need it
to compile. Should it be added with another pull? does it cause breakage
for other installations?

*Jim Dodgen*

**Pull request closed without merging**
